# frozen_string_literal: true
# rbs_inline: enabled

# Normalized token usage for an LLM API call. Buckets carry the same
# meaning for every provider.
class Riffer::Providers::TokenUsage
  # Number of tokens entering the context window, including cache reads and writes.
  attr_reader :input_tokens #: Integer

  # Number of tokens generated by the model, including reasoning/thinking tokens.
  attr_reader :output_tokens #: Integer

  # Subset of +input_tokens+ written to the provider's prompt cache, when the provider reports it.
  attr_reader :cache_write_tokens #: Integer?

  # Subset of +input_tokens+ read from the provider's prompt cache, when the provider reports it.
  attr_reader :cache_read_tokens #: Integer?

  #--
  #: (input_tokens: Integer, output_tokens: Integer, ?cache_write_tokens: Integer?, ?cache_read_tokens: Integer?) -> void
  def initialize(input_tokens:, output_tokens:, cache_write_tokens: nil, cache_read_tokens: nil)
    @input_tokens = input_tokens
    @output_tokens = output_tokens
    @cache_write_tokens = cache_write_tokens
    @cache_read_tokens = cache_read_tokens
  end

  # Returns the total number of tokens (input + output).
  #
  #--
  #: () -> Integer
  def total_tokens
    input_tokens + output_tokens
  end

  # Combines two TokenUsage objects for cumulative tracking.
  #
  #--
  #: (Riffer::Providers::TokenUsage) -> Riffer::Providers::TokenUsage
  def +(other)
    Riffer::Providers::TokenUsage.new(
      input_tokens: input_tokens + other.input_tokens,
      output_tokens: output_tokens + other.output_tokens,
      cache_write_tokens: add_nullable(cache_write_tokens, other.cache_write_tokens),
      cache_read_tokens: add_nullable(cache_read_tokens, other.cache_read_tokens)
    )
  end

  # Converts the token usage to a hash; cache tokens are omitted when nil.
  #--
  #: () -> Hash[Symbol, Integer]
  def to_h
    hash = {input_tokens: input_tokens, output_tokens: output_tokens}
    hash[:cache_write_tokens] = cache_write_tokens if cache_write_tokens
    hash[:cache_read_tokens] = cache_read_tokens if cache_read_tokens
    hash
  end

  private

  #--
  #: (Integer?, Integer?) -> Integer?
  def add_nullable(a, b)
    return nil if a.nil? && b.nil?
    (a || 0) + (b || 0)
  end
end
