# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: riffer/v1/riffer.proto for package 'Riffer.Rpc.V1'

require 'grpc'
require 'riffer/rpc/v1/riffer_pb'

module Riffer
  module Rpc
    module V1
      module RifferAgent
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'riffer.v1.RifferAgent'

          # Start a new agent run. Returns immediately with a RunHandle.
          # The agent loop runs in the background and calls RifferCallback
          # methods on the client synchronously as events occur.
          rpc :StartRun, ::Riffer::Rpc::V1::StartRunRequest, ::Riffer::Rpc::V1::RunHandle
          # Resume a previously interrupted run. Returns immediately.
          # The server reconstructs state from the provided messages,
          # handles pending tool calls, then re-enters the LLM loop.
          rpc :ResumeRun, ::Riffer::Rpc::V1::ResumeRunRequest, ::Riffer::Rpc::V1::RunHandle
          # Interrupt a running agent loop. Maps to throw(:riffer_interrupt).
          # The interrupt is delivered asynchronously; the current blocking
          # callback will complete, then the loop stops.
          rpc :InterruptRun, ::Riffer::Rpc::V1::InterruptRunRequest, ::Riffer::Rpc::V1::InterruptRunResponse
          # Poll run status (optional, since callbacks are the primary channel).
          rpc :GetRunStatus, ::Riffer::Rpc::V1::GetRunStatusRequest, ::Riffer::Rpc::V1::GetRunStatusResponse
          # List registered agents.
          rpc :ListAgents, ::Riffer::Rpc::V1::ListAgentsRequest, ::Riffer::Rpc::V1::ListAgentsResponse
        end

        Stub = Service.rpc_stub_class
      end
      module RifferCallback
        class Service

          include ::GRPC::GenericService

          self.marshal_class_method = :encode
          self.unmarshal_class_method = :decode
          self.service_name = 'riffer.v1.RifferCallback'

          # A new message was added to the conversation.
          # Called for both assistant messages and tool result messages.
          # The client can trigger an interrupt via the response.
          rpc :OnMessage, ::Riffer::Rpc::V1::OnMessageRequest, ::Riffer::Rpc::V1::OnMessageResponse
          # A streaming event occurred during LLM generation.
          # Only called when streaming=true.
          rpc :OnStreamEvent, ::Riffer::Rpc::V1::OnStreamEventRequest, ::Riffer::Rpc::V1::OnStreamEventResponse
          # Execute a tool call. The agent loop blocks until this returns.
          rpc :ExecuteTool, ::Riffer::Rpc::V1::ExecuteToolRequest, ::Riffer::Rpc::V1::ExecuteToolResponse
          # Execute a guardrail. The agent loop blocks until this returns.
          # The client runs the guardrail logic and returns pass/transform/block.
          rpc :ExecuteGuardrail, ::Riffer::Rpc::V1::ExecuteGuardrailRequest, ::Riffer::Rpc::V1::ExecuteGuardrailResponse
          # A guardrail modified or blocked the conversation.
          rpc :OnGuardrailEvent, ::Riffer::Rpc::V1::OnGuardrailEventRequest, ::Riffer::Rpc::V1::OnGuardrailEventResponse
          # The agent run completed (or was interrupted/blocked).
          # Delivers the final accumulated state.
          rpc :OnRunComplete, ::Riffer::Rpc::V1::OnRunCompleteRequest, ::Riffer::Rpc::V1::OnRunCompleteResponse
        end

        Stub = Service.rpc_stub_class
      end
    end
  end
end
