name: ci

on:
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/lint

  test:
    runs-on: ubuntu-latest
    name: test ${{ matrix.ruby }}

    strategy:
      matrix:
        ruby:
          - "3.3"
          - "3.4"
          - "4.0"

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bin/test

  test-no-otel:
    runs-on: ubuntu-latest

    env:
      BUNDLE_WITHOUT: opentelemetry

    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bin/test

  rbs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Generate RBS files
        run: bin/rbs
      - name: Check for RBS drift
        run: git diff --exit-code sig/generated/
      - name: Run Steep type check
        run: bin/typecheck
